awe:
  #Do not change!
  version: 3
  rendering:
    #Amount of time (in ticks) the server will place a chunk of blocks
    interval: 15
    #How often that a user will get an update on the current queue (number of intervals)
    talk-interval: 10
    #Maximum size of the blocks queue
    queue-max-size: 10000000
  dispatcher:
    #Maximum number of jobs performed in one run
    max-jobs: 2000
    #Maximum number of idle runs before disabling the dispatcher
    max-idle-runs: 200
    #Maximum number of miliseconds the dispatcher can use
    #This value should be lower than 50% of 1 tick (25ms)
    max-time: 20
  #Maximum number of blocks in queue mode before AWE forces block placing
  #Use -1 to disable force flush.
  forceFlushBlocks: 10000
  #Check for updates
  checkVersion: true
  #Disable or Enable block physics freeze when placing blocks
  physicsFreez: true
  #File containing all the messages
  strings: "english.yml"
  #Show debug messages
  debug: false
  #Blocks hub plugin options
  blocksHub:
    #Enable block change logging
    logBlocks: true
    #Enable blocks access control
    checkAccess: false
  #Player permission groups.
  #Permission node: AWE.Groups.<group name>
  permissionGroups:
    #The group entry (at least one group is required!)
    #If a player has multiple groups, the last one defined in the config
    #is assigned. (Lower the group the lower the 'weight' if you can compare it to PEX)
    default:
      #Indicates that the group is called default.
      #Only one group can be default, if multiple groups are set to default
      #the first one is used as default. The default group is used for players
      #that do not have any other permission groups assigned to them.
      isDefault: true
      #Maximum number of jobs a player can have.
      #Set to -1 for no job limit
      maxJobs: 1
      #Enable or disable auto job cancelation on player quit
      cleanOnLogout: true
      #Default AWE status for logging in players
      defaultMode: on
      renderer:
        #blocks to place (per-interval), this determines the max speed of block placing.
        #If you experience any lag, then lower this and the next property (time).
        #Set to -1 for no limit
        blocks: 10000
        #Maximum number of miliseconds spent on placing blocks.
        #Set to -1 for no limit
        time: 75
      queue:
        #maximum size of the player block queue
        limit-hard: 500000
        #number of blocks on the player queue required to stop placing blocks
        limit-soft: 250000
      messages:
        #Whether or not to show progress using BarAPI
        progress-bar: true
        #Whether or not to show progress using the chat messages
        progress-chat: true
        #Is async world edit talkative
        talkative: true
#Example of additional vip group:
#    vip:
#      #you can remove this, the isDefault is set to false by default
#      isDefault: false
#      maxJobs: -1
#      cleanOnLogout: false
#      #You can omit entries that are same value as in the default group.
#      #For example, if you dont include the following property then AWE
#      #will use the proerty value from the default group.
#      #defaultMode: on (This has been omitted, so it will use the default group value.)
#      renderer:
#        blocks: 20000
#        time: -1
  #AWE will make the following WorldEdit actions asynchronous
  enabledOperations:
    - undo
    - redo
    - fillXZ
    - removeAbove
    - removeBelow
    - removeNear
    - setBlocks
    - replaceBlocks
    - makeCuboidFaces
    - makeCuboidWalls
    - overlayCuboidBlocks
    - naturalizeCuboidBlocks
    - stackCuboidRegion
    - moveCuboidRegion
    - drainArea
    - fixLiquid
    - makeCylinder
    - makeSphere
    - makePyramid
    - thaw
    - simulateSnow
    - green
    - makePumpkinPatches
    - makeForest
    - makeShape
    - deformRegion
    - hollowOutRegion
    - paste
    - copy
    - cut
    - regenerate
    - center
    - drawLine
    - drawSpline
    - makeBiomeShape
    - forest
    - flora
    - setBiome
    - loadSchematic
    - saveSchematic
    - craftScript
    - makeFaces
    - makeWalls
    - overlayBlocks
    - naturalizeBlocks
    - stackRegion
    - moveRegion
