name: AsyncWorldEdit
main: org.primesoft.asyncworldedit.AsyncWorldEditBukkit
version: 2.3.1
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin attaches into WorldEdit and makes it asynchronous.
authors: [SBPrime]
depend: [WorldEdit]
softdepend: [BlocksHub]
commands:
  awe:
    description: 'Displays the help for Async world edit.'
    usage: /<command>
    aliases: /awe
permissions:
