name: AsyncWorldEdit-BountifulAPI
main: org.primesoft.asyncworldedit.progressDisplay.BountifulAPIBackend
version: 2.3.0
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin provides BountifulAPI progress display backend for AsyncWorldEdit
authors: [SBPrime]
depend: [AsyncWorldEdit, BountifulAPI]

